# Setup
title:               Katt's D&D Game
tagline:             'No, like Actual D&D'
description:         'A nifty website to hold a bunch of notes for Katt, and players, in a nice way.  Because we deserve nice things.'
url:                 https://www.dragons.wtf
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Katt
  url:               https://katt.rocks
  email:             gm@dragons.wtf

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
